[package]
name = "alloy-flashbots"
version = "0.0.1"
authors = ["leruaa"]
license = "MIT"
edition = "2021"
readme = "./README.md"
documentation = "https://docs.rs/alloy-flashbots"
repository = "https://github.com/leruaa/alloy-flashbots"
homepage = "https://github.com/leruaa/alloy-flashbots"
description = """
Alloy transport to send transaction bundles via Flashbots.
"""

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy", features = [
    "rpc",
    "rpc-client",
    "json-rpc",
    "rpc-types",
    "rpc-types-eth",
    "network",
    "providers",
    "transports",
    "transport-http",
    "signers",
] }
serde = "1.0"
hyper = { version = "1.1", features = ["client"] }
tower = "0.4"
reqwest = { version = "0.12", optional = true }
url = "2.5"
serde_json = "1.0"
async-trait = "0.1"

[dev-dependencies]
dotenv = "0.15"
tokio = { version = "1", features = ["rt", "macros"] }
alloy = { git = "https://github.com/alloy-rs/alloy", features = [
    "rpc-client",
    "consensus",
    "signer-wallet",
] }
