[package]
name = "alloy-flashbots"
version = "0.0.1"
edition = "2021"

[dependencies]
alloy-primitives = "0.6"
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy", rev = "11b8031" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "11b8031" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "11b8031" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "11b8031" }
hyper = { version = "1.1", features = ["client"] }
tower = "0.4"
reqwest = { version = "0.11" }
serde_json = "1.0"
