[package]
name = "alloy-flashbots"
version = "0.0.1"
authors = ["leruaa"]
license = "MIT"
edition = "2021"
readme = "./README.md"
documentation = "https://docs.rs/alloy-flashbots"
repository = "https://github.com/leruaa/alloy-flashbots"
homepage = "https://github.com/leruaa/alloy-flashbots"
description = """
Alloy transport to send transaction bundles via Flashbots.
"""

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]

[dependencies]
alloy-primitives = "0.6"
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-providers = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
serde = "1.0"
hyper = { version = "1.1", features = ["client"] }
tower = "0.4"
reqwest = { version = "0.11", optional = true }
serde_json = "1.0"
async-trait = "0.1"

[dev-dependencies]
dotenv = "0.15"
tokio = { version = "1", features = ["rt", "macros"] }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "05d0d0e" }
